catalog:
  '@nolebase/vitepress-plugin-git-changelog': ^2.18.0
  '@vite-pwa/vitepress': ^1.0.0
  ant-design-vue: ^4.2.6
  lucide-vue-next: ^0.507.0
  medium-zoom: ^1.1.0
  radix-vue: ^1.9.17
  vitepress: ^1.6.3
  vitepress-plugin-group-icons: ^1.6.1
  vue: ^3.5.17
